---
- name: Install Vim, PHP, MySQL, Memcached, Node, the MySQL client, and Nginx
  hosts: choochoo_local
  remote_user: root
  become: yes

  roles:
    - common
    - vim
    - memcached
    - php-fpm
    - node
    - mysql
    - nginx
    - api
